# Generated by Django 3.1.1 on 2020-09-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlcompany',
            name='company_url',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crawlcompany',
            name='company_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='crawlcompany',
            name='url',
            field=models.CharField(db_index=True, max_length=2048),
        ),
    ]
