# Generated by Django 3.1.1 on 2020-09-24 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodeapp', '0002_auto_20200924_1221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrawlCompany',
            new_name='UrlWc',
        ),
    ]
